### ISSUE TITLE
Software 

### ISSUE THREAD

**Issue by Kyoshiro28** [herzig/bewegungsfelder#1]
Hi Herzig,
I'm very interesting with your amazing project. I'd like to remake this project for elderly health monitoring. would you like to tell me, what software you use (for esp8266 programming) ?
 thanks.

**Comment by herzig** [comment]
I used eclipse, basically I used the setup described in [http://www.esp8266.com/viewtopic.php?t=820](http://www.esp8266.com/viewtopic.php?t=820) 
It should be no big deal to use other setups or other ESP SDK Versions, with no or only minor changes to the code.

I added a link to the instructions in the README.md
